package web

const reconcileUIScript = `<script>
(function(){
  var reconcileRoots=[],reconcileOutput='',lastReport=null;
  function ensureReconcileUI(){
    if(document.getElementById('reconcileCard'))return;
    var cards=document.querySelectorAll('.card');if(!cards.length)return;
    var sec=document.createElement('section');sec.id='reconcileCard';sec.className='card';sec.innerHTML='<div class="actions"><strong>統合ファイル管理</strong><span class="muted">複数の旧 MangaOrganize ライブラリを横断し、同一シリーズ・同一巻を1つの統合先へまとめます。</span></div><div style="margin-top:10px"><div class="muted">統合元ライブラリ（最大32箇所）</div><div id="reconcileRoots"></div><div class="actions" id="reconcileAddRootRow" style="margin-top:6px"><button id="reconcileAddRoot">＋ フォルダ追加</button></div><div id="reconcileRootBrowserSlot"></div></div><div style="margin-top:10px"><div class="muted">統合先フォルダ（既存ファイルも比較対象として自動解析します）</div><div class="actions" id="reconcileOutputRow"><input id="reconcileOutput" type="text" placeholder="/share/Comics"><button id="reconcileBrowseOutput">フォルダ選択</button></div><div id="reconcileOutputBrowserSlot"></div></div><div class="actions" style="margin-top:10px"><button class="primary" id="reconcileScan">解析</button><button class="accent" id="reconcileRun" disabled>統合を実行</button></div><div id="reconcileSummary" class="muted" style="margin-top:8px"></div><div id="reconcileChoices" class="hidden" style="margin-top:12px"></div><div id="reconcileTableWrap" class="scroll hidden" style="margin-top:10px"><table><thead><tr><th>現在</th><th>シリーズ/巻</th><th>更新日時</th><th>処理</th><th>移動先/理由</th></tr></thead><tbody id="reconcileRows"></tbody></table></div><p class="muted">完全重複はSHA-256で確認します。同一シリーズ・同一巻で内容が異なる場合は更新日時が唯一新しいものを自動採用し、旧版は削除せず隔離します。自動判定できない組だけ最後にまとめて選択します。</p>';
    cards[cards.length-1].parentNode.insertBefore(sec,cards[cards.length-1].nextSibling);
    document.getElementById('reconcileAddRoot').onclick=function(){pickFolder('reconcileRootBrowserSlot','',function(p){if(reconcileRoots.indexOf(p)<0){reconcileRoots.push(p);renderRoots();if(!document.getElementById('reconcileOutput').value)document.getElementById('reconcileOutput').value=p}})};
    document.getElementById('reconcileBrowseOutput').onclick=function(){pickFolder('reconcileOutputBrowserSlot',document.getElementById('reconcileOutput').value,function(p){document.getElementById('reconcileOutput').value=p})};
    document.getElementById('reconcileScan').onclick=scanReconcile;document.getElementById('reconcileRun').onclick=runReconcile;renderRoots();
  }
  function renderRoots(){var el=document.getElementById('reconcileRoots');if(!el)return;if(!reconcileRoots.length){el.innerHTML='<div class="muted" style="padding:6px 0">まだ選択されていません。</div>';return}el.innerHTML=reconcileRoots.map(function(p,i){return '<div class="actions" data-root="'+esc(p)+'" style="margin-top:4px"><code style="flex:1;word-break:break-all">'+esc(p)+'</code><button onclick="removeReconcileRoot('+i+')">削除</button></div>'}).join('')}
  window.removeReconcileRoot=function(i){reconcileRoots.splice(i,1);renderRoots()};
  function pickFolder(slotId,start,done){var browser=document.getElementById('browser'),slot=document.getElementById(slotId);if(!browser||!slot)return;slot.appendChild(browser);browser.classList.remove('hidden');window.inlineBrowserTarget='';browse(start||'').catch(function(){browse('')});var choose=window.chooseCurrent;window.chooseCurrent=function(){var p=browserPath;if(p)done(p);window.chooseCurrent=choose;closeBrowser()}}
  function fmtTime(s){if(!s)return'-';try{return new Date(s).toLocaleString()}catch(e){return s}}
  function shortPath(p,roots){for(var i=0;i<roots.length;i++){if(p.indexOf(roots[i])===0)return '['+(i+1)+'] '+p.slice(roots[i].length).replace(/^\//,'')}return p}
  function renderChoices(r){var wrap=document.getElementById('reconcileChoices'),choices=r.choices||[];if(!choices.length){wrap.classList.add('hidden');wrap.innerHTML='';return}var h='<div class="warn"><strong>要選択 '+choices.length+'グループ</strong> — 自動判定できないものだけ選んでください。</div>';choices.forEach(function(g){h+='<fieldset style="margin-top:8px;border:1px solid #ddd;border-radius:6px"><legend><strong>'+esc(g.series)+(g.has_volume?' 第'+g.volume+'巻':'')+'</strong></legend><div class="muted">'+esc(g.reason||'ユーザー選択が必要')+'</div>';(g.candidates||[]).forEach(function(c){h+='<label style="display:block;padding:6px 0"><input type="radio" name="choice-'+esc(g.id)+'" value="'+esc(c.source)+'"> '+esc(shortPath(c.source,r.roots||[]))+' <span class="muted">更新 '+esc(fmtTime(c.modified_at))+' / '+Math.round((c.size||0)/1048576)+' MiB</span></label>'});h+='</fieldset>'});wrap.innerHTML=h;wrap.classList.remove('hidden')}
  window.scanReconcile=async function(){if(!reconcileRoots.length){alert('統合元フォルダを1つ以上追加してください');return}var output=document.getElementById('reconcileOutput').value.trim()||reconcileRoots[0];var sum=document.getElementById('reconcileSummary');sum.className='muted';sum.textContent='解析中… 同サイズ候補のみSHA-256を確認します。';document.getElementById('reconcileRun').disabled=true;try{var r=await api('api/reconcile/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roots:reconcileRoots,output_root:output})});lastReport=r;reconcileRoots=r.roots||reconcileRoots;reconcileOutput=r.output_root||output;document.getElementById('reconcileOutput').value=reconcileOutput;renderRoots();var s=r.summary||{};sum.textContent='対象 '+(s.files||0)+'件 / 移動 '+(s.move||0)+' / 完全重複 '+(s.duplicates||0)+' / 旧版隔離 '+(s.superseded||0)+' / そのまま '+(s.keep||0)+' / 要選択 '+(s.review||0)+' / 衝突 '+(s.conflicts||0)+' / エラー '+(s.errors||0);renderChoices(r);var h='';(r.items||[]).forEach(function(x){var cls=(x.action==='conflict'||x.action==='error')?'bad':((x.action==='duplicate'||x.action==='superseded'||x.action==='review')?'warn':'');var dest=x.destination?shortPath(x.destination,[r.output_root]):'-';h+='<tr><td>'+esc(shortPath(x.source,r.roots||[]))+'</td><td><strong>'+esc(x.series||'-')+'</strong>'+(x.has_volume?'<div class="muted">第'+x.volume+'巻</div>':'<div class="muted">巻不明</div>')+'</td><td>'+esc(fmtTime(x.modified_at))+'</td><td class="'+cls+'">'+esc(x.action)+(x.auto_selected?'<div class="ok">自動採用</div>':'')+'</td><td>'+esc(dest)+(x.reason?'<div class="muted">'+esc(x.reason)+'</div>':'')+(x.duplicate_of?'<div class="muted">比較元: '+esc(shortPath(x.duplicate_of,r.roots||[]))+'</div>':'')+'</td></tr>'});document.getElementById('reconcileRows').innerHTML=h;document.getElementById('reconcileTableWrap').classList.remove('hidden');document.getElementById('reconcileRun').disabled=(s.move||0)+(s.duplicates||0)+(s.superseded||0)+(s.review||0)===0}catch(e){sum.className='bad';sum.textContent='解析失敗: '+e.message}};
  function collectSelections(){var out={};if(!lastReport)return out;(lastReport.choices||[]).forEach(function(g){var el=document.querySelector('input[name="choice-'+CSS.escape(g.id)+'"]:checked');if(el)out[g.id]=el.value});return out}
  window.runReconcile=async function(){if(!lastReport)return;var selections=collectSelections(),choices=lastReport.choices||[];if(Object.keys(selections).length!==choices.length){alert('要選択グループをすべて選択してください。');document.getElementById('reconcileChoices').scrollIntoView({behavior:'smooth'});return}if(!confirm('複数ライブラリを統合します。\n採用しなかった完全重複・旧版は削除せず隔離します。よろしいですか？'))return;var b=document.getElementById('reconcileRun');b.disabled=true;var sum=document.getElementById('reconcileSummary');sum.textContent='統合中…';try{var r=await api('api/reconcile/execute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roots:reconcileRoots,output_root:reconcileOutput,selections:selections})});sum.textContent='完了: 移動 '+(r.moved||0)+' / 隔離 '+(r.quarantined||0)+' / スキップ '+(r.skipped||0)+' / エラー '+((r.errors||[]).length);await scanReconcile()}catch(e){sum.className='bad';sum.textContent='実行失敗: '+e.message;b.disabled=false}};
  ensureReconcileUI();
})();
</script>
`
