package web

const reconcileUIScript = `<script>
(function(){
  var reconcileRoot='';
  function ensureReconcileUI(){
    if(document.getElementById('reconcileCard'))return;
    var cards=document.querySelectorAll('.card');if(!cards.length)return;
    var sec=document.createElement('section');sec.id='reconcileCard';sec.className='card';sec.innerHTML='<div class="actions"><strong>既存ライブラリ整理</strong><span class="muted">旧 MangaOrganize.py などで整理済みのフォルダを、最新のシリーズ判定で再統合します。</span></div><div class="actions" style="margin-top:10px"><input id="reconcileRoot" type="text" placeholder="/share/Comics"><button id="reconcileBrowse">フォルダ選択</button><button class="primary" id="reconcileScan">解析</button><button class="accent" id="reconcileRun" disabled>整理を実行</button></div><div id="reconcileSummary" class="muted" style="margin-top:8px"></div><div id="reconcileTableWrap" class="scroll hidden" style="margin-top:10px"><table><thead><tr><th>現在</th><th>シリーズ</th><th>処理</th><th>移動先/理由</th></tr></thead><tbody id="reconcileRows"></tbody></table></div><p class="muted">ZIP/RARは再圧縮しません。完全重複は同サイズ候補だけSHA-256で確認し、削除せず <code>.docExtractor-duplicates</code> に隔離します。既存出力との不一致衝突は自動上書きしません。</p>';
    cards[cards.length-1].parentNode.insertBefore(sec,cards[cards.length-1].nextSibling);
    document.getElementById('reconcileBrowse').onclick=openReconcileBrowser;document.getElementById('reconcileScan').onclick=scanReconcile;document.getElementById('reconcileRun').onclick=runReconcile;
  }
  window.openReconcileBrowser=async function(){var browser=document.getElementById('browser');if(!browser)return;browser.classList.remove('hidden');var p=document.getElementById('reconcileRoot').value;try{await browse(p)}catch(e){await browse('')};var choose=window.chooseCurrent;window.chooseCurrent=function(){if(browserPath)document.getElementById('reconcileRoot').value=browserPath;window.chooseCurrent=choose;closeBrowser()}};
  window.scanReconcile=async function(){var root=document.getElementById('reconcileRoot').value.trim();if(!root)return;var sum=document.getElementById('reconcileSummary');sum.textContent='解析中…（同サイズ重複候補がある場合はSHA-256確認のため時間がかかることがあります）';document.getElementById('reconcileRun').disabled=true;try{var r=await api('api/reconcile/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({root:root})});reconcileRoot=r.root;var s=r.summary||{};sum.textContent='対象 '+(s.files||0)+'件 / 移動 '+(s.move||0)+' / 重複隔離 '+(s.duplicates||0)+' / そのまま '+(s.keep||0)+' / 衝突 '+(s.conflicts||0)+' / エラー '+(s.errors||0);var h='';(r.items||[]).forEach(function(x){var cls=x.action==='conflict'||x.action==='error'?'bad':(x.action==='duplicate'?'warn':'');var dest=x.destination?x.destination.replace(r.root,'').replace(/^\//,''):'-';h+='<tr><td>'+esc(x.relative)+'</td><td><strong>'+esc(x.series||'-')+'</strong><div class="muted">'+Math.round((x.confidence||0)*100)+'%</div></td><td class="'+cls+'">'+esc(x.action)+'</td><td>'+esc(dest)+(x.reason?'<div class="muted">'+esc(x.reason)+'</div>':'')+(x.duplicate_of?'<div class="muted">重複元: '+esc(x.duplicate_of)+'</div>':'')+'</td></tr>'});document.getElementById('reconcileRows').innerHTML=h;document.getElementById('reconcileTableWrap').classList.remove('hidden');document.getElementById('reconcileRun').disabled=(s.move||0)+(s.duplicates||0)===0}catch(e){sum.className='bad';sum.textContent='解析失敗: '+e.message}};
  window.runReconcile=async function(){if(!reconcileRoot)return;if(!confirm('プレビューされた安全な移動と完全重複の隔離を実行します。\nファイル削除は行いません。よろしいですか？'))return;var b=document.getElementById('reconcileRun');b.disabled=true;var sum=document.getElementById('reconcileSummary');sum.textContent='整理中…';try{var r=await api('api/reconcile/execute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({root:reconcileRoot})});sum.textContent='完了: 移動 '+(r.moved||0)+' / 重複隔離 '+(r.quarantined||0)+' / スキップ '+(r.skipped||0)+' / エラー '+((r.errors||[]).length);await scanReconcile()}catch(e){sum.className='bad';sum.textContent='実行失敗: '+e.message;b.disabled=false}};
  ensureReconcileUI();
})();
</script>
`
