package web

import "strings"

const reconcileResumeUIScript = `<script id="docExtractorReconcileResumeScript">
(function(){
 var restoredSelections={manage:{},reprocess:{}};
 function fmt(ms){ms=Number(ms||0);if(ms<=0)return'-';var s=Math.round(ms/1000);if(s<60)return s+'秒';var m=Math.floor(s/60);if(m<60)return m+'分 '+(s%60)+'秒';return Math.floor(m/60)+'時間 '+(m%60)+'分'}
 function phaseName(p){return({starting:'開始中',counting:'対象確認中',inspecting:'ファイル名解析中',clustering:'シリーズ名統合中',duplicates:'SHA-256重複確認中',variants:'同巻バリアント判定中',saving:'解析結果保存中',executing:'ファイル整理実行中',done:'完了',failed:'失敗',cancelled:'停止済み'})[p]||p||'待機中'}
 function progressID(mode){return mode==='reprocess'?'reprocessProgress':'manageProgress'}
 function summaryID(mode){return mode==='reprocess'?'reprocessSummary':'reconcileSummary'}
 function runID(mode){return mode==='reprocess'?'reprocessRun':'reconcileRun'}
 function q(id){return document.getElementById(id)}
 function renderProgress(mode,s){var id=progressID(mode),pct=Math.max(0,Math.min(100,Number(s.overall_progress||0)*100));if(!q(id+'Title'))return;q(id+'Title').textContent=phaseName(s.phase);q(id+'Msg').textContent=s.message||'';q(id+'Count').textContent=Number(s.completed||0)+' / '+(Number(s.total||0)||'-');q(id+'Pct').textContent=Math.round(pct)+'%';q(id+'Elapsed').textContent=fmt(s.elapsed_ms);q(id+'Eta').textContent=s.running&&s.estimated_remaining_ms?fmt(s.estimated_remaining_ms):(s.phase==='done'?'0秒':'-');q(id+'Rate').textContent=s.items_per_second?Number(s.items_per_second).toFixed(2)+' 件/秒':'-';q(id+'Bar').style.width=pct+'%'}
 function renderSummary(mode,s){var el=q(summaryID(mode));if(!el)return;if(s.error){el.className='bad';el.textContent='処理失敗: '+s.error;return}if(s.phase==='cancelled'){el.className='warn';el.textContent='サーバー側の処理を停止しました。';return}if(s.kind==='execute'&&s.phase==='done'){api('api/reconcile/async/result?mode='+mode).then(function(r){var x=r.result||{};el.className='muted';el.textContent='完了: 移動 '+(x.moved||0)+' / 隔離 '+(x.quarantined||0)+' / スキップ '+(x.skipped||0)+' / エラー '+((x.errors||[]).length)});return}var x=s.summary||{};if(!s.items&&!x.files){if(s.running)el.textContent='サーバー側で'+phaseName(s.phase)+'です。';return}el.className='muted';el.textContent='対象 '+(x.files||0)+'件 / 移動 '+(x.move||0)+' / 完全重複 '+(x.duplicates||0)+' / 旧版隔離 '+(x.superseded||0)+' / そのまま '+(x.keep||0)+' / 要選択 '+(x.review||0)+' / 衝突 '+(x.conflicts||0)+' / エラー '+(x.errors||0)}
 async function renderItems(mode){var r=await api('api/reconcile/async/items?mode='+mode+'&offset=0&limit=100'),rows=mode==='reprocess'?q('reprocessRows'):q('reconcileRows'),wrap=mode==='reprocess'?q('reprocessTableWrap'):q('reconcileTableWrap');if(!rows||!wrap)return;var h='';(r.items||[]).forEach(function(x){h+='<tr><td>'+esc(x.relative||x.source)+'</td><td><strong>'+esc(x.series||'-')+'</strong>'+(x.has_volume?'<div class="muted">第'+x.volume+'巻</div>':'')+'</td>'+(mode==='manage'?'<td>'+esc(x.modified_at||'-')+'</td>':'')+'<td>'+esc(x.action||'-')+'</td><td>'+esc(x.reason||x.destination||'-')+'</td></tr>'});rows.innerHTML=h;wrap.classList.toggle('hidden',!r.total)}
 async function renderChoices(){var st=await api('api/reconcile/async/status?mode=manage'),total=Number(st.choices||0),wrap=q('reconcileChoices');if(!wrap)return;if(!total){wrap.classList.add('hidden');wrap.innerHTML='';return}var all=[];for(var off=0;off<total;off+=500){var r=await api('api/reconcile/async/choices?mode=manage&offset='+off+'&limit=500');all=all.concat(r.choices||[])}var h='<div class="warn"><strong>要選択 '+total+'グループ</strong> — 直前解析結果から復元しました。</div>';all.forEach(function(g){h+='<fieldset style="margin-top:8px"><legend><strong>'+esc(g.series)+(g.has_volume?' 第'+g.volume+'巻':'')+'</strong></legend>';(g.candidates||[]).forEach(function(c){h+='<label style="display:block;padding:5px"><input type="radio" data-restore-group="'+esc(g.id)+'" name="restore-'+esc(g.id)+'" value="'+esc(c.source)+'"> '+esc(c.relative||c.source)+'</label>'});h+='</fieldset>'});wrap.innerHTML=h;wrap.classList.remove('hidden');wrap.querySelectorAll('[data-restore-group]').forEach(function(x){x.onchange=function(){restoredSelections.manage[x.dataset.restoreGroup]=x.value}})}
 async function executeRestored(mode){var st=await api('api/reconcile/async/status?mode='+mode);if(st.running){alert('サーバー側で処理中です。状態反映または停止を使用してください。');return}if(!st.items){alert('適用できる解析結果がありません。');return}if(mode==='manage'&&st.choices&&Object.keys(restoredSelections.manage).length<st.choices){alert('要選択グループをすべて選択してください。');return}if(!confirm('直前の解析結果を使って整理を実行します。よろしいですか？'))return;await api('api/reconcile/async/execute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:mode,selections:restoredSelections[mode]||{}})});await attach(mode)}
 async function applyState(mode){var s=await api('api/reconcile/async/status?mode='+mode);renderProgress(mode,s);renderSummary(mode,s);var stop=q('reconcileStop-'+mode),apply=q('reconcileApply-'+mode),run=q(runID(mode));if(stop)stop.disabled=!s.running;if(apply)apply.textContent=s.running?'実行中の状態を反映':'直前の解析結果を再適用';if(s.roots&&s.roots.length&&mode==='reprocess'&&q('reprocessRoot'))q('reprocessRoot').value=s.roots[0];if(s.output_root&&mode==='manage'&&q('reconcileOutput'))q('reconcileOutput').value=s.output_root;if(!s.running&&s.items){await renderItems(mode);if(mode==='manage'&&s.choices)await renderChoices();var x=s.summary||{},actions=(x.move||0)+(x.duplicates||0)+(x.superseded||0)+(x.review||0);if(run){run.disabled=!actions||(mode==='reprocess'&&(x.review||0)>0);run.onclick=function(){executeRestored(mode)}}}return s}
 async function attach(mode){try{var s=await applyState(mode);while(s.running){await new Promise(function(r){setTimeout(r,1000)});s=await applyState(mode)}await applyState(mode)}catch(e){var el=q(summaryID(mode));if(el){el.className='bad';el.textContent='状態取得失敗: '+e.message}}}
 async function stop(mode){if(!confirm('サーバー側で実行中の処理を停止しますか？'))return;try{await api('api/reconcile/async/stop?mode='+mode,{method:'POST'});await attach(mode)}catch(e){alert('停止要求に失敗しました: '+e.message)}}
 function installMode(mode){var card=q(mode==='reprocess'?'reprocessCard':'reconcileCard');if(!card||q('reconcileApply-'+mode))return;var run=q(runID(mode));if(!run)return;var row=run.closest('.actions');if(!row)return;var apply=document.createElement('button');apply.id='reconcileApply-'+mode;apply.textContent='直前の解析結果を再適用';apply.onclick=function(){attach(mode)};var stopb=document.createElement('button');stopb.id='reconcileStop-'+mode;stopb.textContent='サーバー処理を停止';stopb.disabled=true;stopb.onclick=function(){stop(mode)};row.appendChild(apply);row.appendChild(stopb);attach(mode)}
 function install(){installMode('reprocess');installMode('manage')}
 setInterval(install,1000);setTimeout(install,50)
})();
</script>`

func init() {
	indexHTML = strings.Replace(indexHTML, "</body>", reconcileResumeUIScript+"</body>", 1)
}
